sylius_resource:
    resources:
        app.supplier:
            driver: doctrine/orm
            classes:
                model: App\Entity\Supplier
                repository: App\Doctrine\ORM\SupplierRepository
                form: App\Form\Type\SupplierType
