app_admin_supplier:
    resource: |
        alias: app.supplier
        section: admin
        templates: "@SyliusAdmin/Crud"
        redirect: update
        grid: app_admin_supplier
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: '/%sylius_admin.path_name%'
    
app_admin_supplier_accept:
    path: '/%sylius_admin.path_name%/{id}/accept'
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: accept
            redirect: referer
            flash: app.supplier.accept

app_admin_supplier_reject:
    path: '/%sylius_admin.path_name%/supplier/{id}/reject'
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: reject
            redirect: referer
            flash: app.supplier.reject

app_admin_ajax_promotion_by_name:
    path: '/%sylius_admin.path_name%/ajax/promotion/search'
    methods: [GET]
    defaults:
        _controller: sylius.controller.promotion:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    name: $name

app_admin_ajax_promotion_by_codes:
    path: '/%sylius_admin.path_name%/ajax/promotion/codes'
    methods: [GET]
    defaults:
        _controller: sylius.controller.promotion:indexAction
        _format: json
        _sylius:
            serialization_groups: [Default]
            permission: true
            repository:
                method: findByCode
                arguments:
                    - $code
