app_shop_one_click_checkout:
    path: /{_locale}/checkout/one-click/{variantId}
    defaults:
        _controller: App\Controller\OneClickCheckoutController:buyNowAction
        # Due to the CheckoutResolver we need to set the state_machine graph
        # and transition used to do this operation
        _sylius:
            state_machine:
                graph: sylius_order_checkout
                transition: address

app_checkout_iban:
    path: /{_locale}/checkout/iban
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order::updateAction
        _sylius:
            event: ibaned
            flash: true
            template: "Shop/Checkout/Iban/iban.html.twig"
            form: App\Form\Type\OrderIbanType
            repository:
                method: findCartForAddressing
                arguments:
                    - "expr:service('sylius.context.cart').getCart().getId()"
            state_machine:
                graph: sylius_order_checkout
                transition: iban
