app_admin_supplier:
    resource: |
        alias: app.supplier
        section: admin
        templates: "@SyliusAdmin/Crud"
        redirect: update
        grid: app_admin_supplier
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: '/%sylius_admin.path_name%'
    
app_admin_supplier_accept:
    path: '/%sylius_admin.path_name%/{id}/accept'
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: accept
            redirect: referer
            flash: app.supplier.accept

app_admin_supplier_reject:
    path: '/%sylius_admin.path_name%/supplier/{id}/reject'
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: reject
            redirect: referer
            flash: app.supplier.reject
